### ISSUE TITLE
Give support of  EFS (Elastic File Service) mount.

### ISSUE THREAD

**Issue by Gouravdeep** [aws/apprunner-roadmap#80] opened 2021-10-04 19:06 UTC
Please give support of EFS  (Elastic File Service) mount.

**Comment by andymac4182** [comment] 2021-10-06 10:33
I believe this will be pending support for VPC https://github.com/aws/apprunner-roadmap/issues/1

**Comment by RubberChickenParadise** [comment] 2021-11-15 19:42
also duplicate of #14

**Comment by mwarkentin** [comment] 2022-02-08 20:48
VPC support just landed, hopefully that unlocks this soon!

**Closed** 2022-08-17 07:07 UTC

**Comment by bev-s** [comment] 2022-11-16 11:48
Plus 1
