### ISSUE TITLE
Add a feature in AppRunner service which will allow to increase the ephemeral storage

### ISSUE THREAD

**Issue by raesquiv360** [aws/apprunner-roadmap#178] opened 2023-03-24 20:18 UTC
**Community Note**
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do * not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
We would like to be able to increase the ephemeral storage so more than 3 GB can be used.

**Describe alternatives you've considered**
For now, we can use ECS service as alternative approach.

**Additional context**
Anything else we should know?
As mentioned in https://docs.aws.amazon.com/apprunner/latest/dg/develop.html#develop.considerations increasing the storage limit will allow us to use container images that exceed 3Gb and also have space to store and work with large files

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by amitgupta85** [comment] 2023-05-23 21:54
What would be a reasonable ephemeral storage that you would like us to support?

**Comment by jsheld** [comment] 2023-05-25 18:44
Issue 112 is asking for the same: https://github.com/aws/apprunner-roadmap/issues/112. Closing this issue as it is a duplicate of that one.

**Closed by jsheld** 2023-05-25 18:44 UTC

**Comment by asford** [comment] 2023-08-14 22:41
@jsheld It doesn't appear that #112 is asking for the same feature.
Right now the AppRunner ephemeral storage limit, and resulting container image size limit, is well documented at 3gb.
However the storage limit is quite lower than:
* The Fargate 1.4.0 platform minimum (20GB) https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html
* The lambda container image size limit (10gb) https://docs.aws.amazon.com/lambda/latest/dg/images-create.html
* Comparable limits in Google Cloud Run (at least 32GB) https://cloud.google.com/run/quotas

This is a near blocker for some scientific software applications, as a standard image for python scientific/numeric computing is at or beyond a 3gb image size.
For calibration, [continuumio/anaconda3](https://hub.docker.com/r/continuumio/anaconda3/tags) is a representative base image designed to support low-effort scientific python applications using the anaconda ecosystem.
The image is ~1.5gb compressed, and ~5gb uncompressed.
It launches comfortably in standard fargate environments, but isn't compatible with AppRunner's stated limits.

This is obviously a pretty large image, but it's standard practice for simple projects in data science applications to include a relatively large base image.
Given that AppRunner targets a simplified deployment story, it'd be extremely useful to be able to host these classes of simple applications in AppRunner.

**Comment by msamsami** [comment] 2023-10-05 11:45
Any updates on this issue?
3 GB is not enough storage for many applications, especially those involved with language models, computer vision, GPU, etc.

I'm getting this error while building my app on App Runner which I assume is because of storage issue:

```

2023-10-05T14:38:53.808+03:30 | [Build] Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
-- | --
| 2023-10-05T14:38:53.808+03:30 | [Build] Collecting nvidia-cuda-nvrtc-cu12==12.1.105
| 2023-10-05T14:38:53.808+03:30 | [Build] Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
| 2023-10-05T14:38:53.808+03:30 | [Build] Collecting nvidia-cudnn-cu12==8.9.2.26
| 2023-10-05T14:38:53.808+03:30 | [Build] Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
| 2023-10-05T14:38:53.808+03:30 | [Build] /root/.pyenv/pyenv.d/exec/pip-rehash/pip: line 20: 403 Killed "$PYENV_COMMAND_PATH" "$@"
| 2023-10-05T14:39:02.803+03:30 | [AppRunner] Failed to deploy your application source code.
```

**Comment by GitNilsKrause** [comment] 2023-12-30 00:42
Could you please consider increasing the default size of the ephemeral storage, or provide an option to configure its size? This enhancement would significantly boost AWS's appeal in comparison to GCP's App Engine.
